version: '3.6'

services:
  icb-chain-db:
    image: mongo:4.2.3-bionic
    container_name: icbchaindb
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_ROOT_DATABASE=${MONGO_ROOT_DATABASE}
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_ROOT_USER}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_ROOT_PASSWORD}
      - MONGO_INITDB_USERNAME=${MONGO_INITDB_USERNAME}
      - MONGO_INITDB_PASSWORD=${MONGO_INITDB_PASSWORD}
      - MONGO_INITDB_DATABASE=${MONGO_INITDB_DATABASE}
    volumes:
      # seeding scripts
      - ./config/mongo/mongo-entrypoint:/docker-entrypoint-initdb.d
      # named volumes
      - ./config/mongo/mongodb:/data/db
      - ./config/mongo/mongoconfig:/data/configdb
    networks:
       mongo_net:
        aliases:
          - icb-chain-db

  icb-network:
    image: docker-dev.icbcrypto.services/icb-network-cahin-api:latest
    container_name: icb-network
    ports: 
      - 5030:5030
      - 5031:5031
    environment:
      - DBSetting__ConnectionString=mongodb://${MONGO_INITDB_USERNAME}:${MONGO_INITDB_PASSWORD}@icbchaindb:27017
      - DBSetting__DatabaseName=${MONGO_INITDB_DATABASE}
      - GRPC__WEB_PORT=${GRPC__WEB_PORT}
      - GRPC__PORT=${GRPC__PORT}
      - AppEnv__Passphrase=${AppEnv__Passphrase}
      - AppEnv__NodeAddress=${AppEnv__NodeAddress}
      - AppEnv__BootstrapPeers=${AppEnv__BootstrapPeers}
    networks:
      mongo_net:
        aliases:
          - icb-network
  
  mongoexpress:
    image: mongo-express
    container_name: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      - ME_CONFIG_MONGODB_SERVER=icbchaindb
      - ME_CONFIG_MONGODB_ADMINUSERNAME=${MONGO_ROOT_USER}
      - ME_CONFIG_MONGODB_ADMINPASSWORD=${MONGO_ROOT_PASSWORD}
      - ME_CONFIG_BASICAUTH_USERNAME=${MONGOEXPRESS_LOGIN}
      - ME_CONFIG_BASICAUTH_PASSWORD=${MONGOEXPRESS_PASSWORD}
      - ME_CONFIG_SITE_BASEURL=/db/
    depends_on:
      - icb-chain-db
    networks:
       mongo_net:
        aliases:
          - mongoexpress

  nginx: 
    image: nginx:latest
    container_name: icb-node-nginx-proxy
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/ssl:/etc/nginx/ssl:ro
      - ./nginx/conf.d:/etc/nginx/conf.d:ro
    restart: always
    ports: 
      - 443:443
      - 80:80
      - 1433:1433
    depends_on:
     - icb-network
     - icb-chain-db
    networks:
      mongo_net:

networks:
  mongo_net:
    driver: bridge
